DROP TABLE IF EXISTS images;
CREATE TABLE IF NOT EXISTS images(
id INTEGER PRIMARY KEY ASC,
name VARCHAR(128) NOT NULL,
path VARCHAR(512) NOT NULL
);
DROP TABLE IF EXISTS image_labels;
CREATE TABLE IF NOT EXISTS image_labels(
 image_id INTEGER,
 label VARCHAR(128) NOT NULL,
 FOREIGN KEY (image_id) REFERENCES images(id)
 );

